// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPPzwCDB58oSG_2kmlwBZtgkI5h5IQCac',
    appId: '1:994110171045:web:e17ec8c6a8f1b46acdea4c',
    messagingSenderId: '994110171045',
    projectId: 'lab03-193193',
    authDomain: 'lab03-193193.firebaseapp.com',
    storageBucket: 'lab03-193193.firebasestorage.app',
    measurementId: 'G-XLNR4HHE1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD71wL5OHrBSPjSTtxSa0dw5q8P5wG78CQ',
    appId: '1:994110171045:android:c9b5f2ef5250480fcdea4c',
    messagingSenderId: '994110171045',
    projectId: 'lab03-193193',
    storageBucket: 'lab03-193193.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATBaDHkYkSAmbn7-xDVQNF74zX2waL2ZY',
    appId: '1:994110171045:ios:f1af663a42f75036cdea4c',
    messagingSenderId: '994110171045',
    projectId: 'lab03-193193',
    storageBucket: 'lab03-193193.firebasestorage.app',
    iosBundleId: 'com.example.lab02193193',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATBaDHkYkSAmbn7-xDVQNF74zX2waL2ZY',
    appId: '1:994110171045:ios:f1af663a42f75036cdea4c',
    messagingSenderId: '994110171045',
    projectId: 'lab03-193193',
    storageBucket: 'lab03-193193.firebasestorage.app',
    iosBundleId: 'com.example.lab02193193',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPPzwCDB58oSG_2kmlwBZtgkI5h5IQCac',
    appId: '1:994110171045:web:7d5f75b3c0b5157ecdea4c',
    messagingSenderId: '994110171045',
    projectId: 'lab03-193193',
    authDomain: 'lab03-193193.firebaseapp.com',
    storageBucket: 'lab03-193193.firebasestorage.app',
    measurementId: 'G-ZVPBKFKKZB',
  );

}